[".config/kitty/kitty-themes"]
    type = "git-repo"
    url = "https://github.com/dexpota/kitty-themes.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
